### ISSUE TITLE
Deploy graphics

### ISSUE THREAD

**Issue by courtney-rosenthal** [tx10indivisible/tx10indivisible-graphics#4]
The graphics need to be deployed to the following locations, in order of priority:

* Facebook
* Twitter
* website
* Action Network
* Youtube

(Most of these are using the Abe Statue graphic, which would be replaced.)

Need to coordinate with Chip on access/credentials.

**Comment by SaraDGore** [comment]
Facebook done.

**Comment by courtney-rosenthal** [comment]
I got Action Network and Youtube.

**Comment by SaraDGore** [comment]
Twitter done.

**Comment by courtney-rosenthal** [comment]
Website done. All items complete.
